### PR TITLE
1218 bug processnetstat is funky

### LINKED ISSUE #1218: [bug] process.netstat() is funky
**Describe the bug**

**To Reproduce**

run `process.netstat()` and compare it to `netstat -ptuna`.... something 🐟 👀 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by hulto**
#### What type of PR is this?
/kind bug
/kind feature

image

#### What this PR does / why we need it:
- Remove dependency on listeners crate
- Adds new netstat lib
- Implements macos, windows, and linux netstat
- Updates windows_sys library

#### Which issue(s) this PR fixes:
Fixes #1218

### CODE REVIEW

File: implants/lib/eldritch/src/process/netstat_impl.rs [hunk 1]
```diff
@@ -1,41 +1,77 @@
...
 use starlark::values::{dict::Dict, Heap};
 
-#[cfg(target_os = "freebsd")]
-pub fn netstat(_: &Heap) -> Result<Vec<Dict>> {
-    Err(anyhow::anyhow!("Not implemented for FreeBSD"))
-}
-
-#[cfg(not(target_os = "freebsd"))]
 pub fn netstat(starlark_heap: &'_ Heap) -> Result<Vec<Dict<'_>>> {
     use super::super::insert_dict_kv;
```
Comment (hulto) [inline implants/lib/eldritch/src/process/netstat_impl.rs:11]: Move to module head.

File: implants/lib/eldritch/src/process/netstat_impl.rs [hunk 2]
```diff
@@ -1,41 +1,77 @@
...
+            "local_port",
+            entry.local_port as u32,
+            u32
+        );
+
+        // remote_address: IP or "UNKNOWN"
+        let remote_addr = entry
+            .remote_address
+            .map(|ip| ip.to_string())
+            .unwrap_or_else(|| "UNKNOWN".to_string());
```
Comment (hulto) [inline implants/lib/eldritch/src/process/netstat_impl.rs]: Move unknown to a const.

File: implants/lib/netstat/src/freebsd.rs [hunk 3]
```diff
@@ -0,0 +1,21 @@
+use super::{ConnectionState, NetstatEntry, SocketType};
+use anyhow::Result;
+
+pub fn netstat() -> Result<Vec<NetstatEntry>> {
+    // TODO: Implement FreeBSD sysctl using net.inet.tcp.pcblist
```
Comment (hulto) [inline implants/lib/netstat/src/freebsd.rs:5]: Implement this.

File: implants/lib/netstat/src/linux.rs [hunk 4]
```diff
@@ -0,0 +1,393 @@
...
+
+fn parse_proc_net_line(
+    line: &str,
+    socket_type: SocketType,
+    is_ipv6: bool,
+    inode_to_pid: &HashMap<u64, u32>,
+) -> Result<Option<NetstatEntry>> {
+    let fields: Vec<&str> = line.split_whitespace().collect();
+
+    if fields.len() < 10 {
```
Comment (hulto) [inline implants/lib/netstat/src/linux.rs]: Not sure 10 is the right number proc net tcp seems to look like. Should maybe be 12.

tcp
```
  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode                                                     
   0: 0100007F:B0FB 00000000:0000 0A 00000000:00000000 00:00000000 00000000  1000        0 1036515 1 0000000000000000 100 0 0 10 0                   
```

tcp6
```
  sl  local_address                         remote_address                        st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode
```

udp
```
   sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode ref pointer drops            
31123: 00000000:DAB3 00000000:0000 07 00000000:00000000 00:00000000 00000000  1000        0 47277 2 0000000000000000 0         
```

udp6
```
  sl  local_address                         remote_address                        st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode ref pointer drops
26016: 00000000000000000000000000000000:C6C0 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000  1000        0 47276 2 0000000000000000 0
```

File: implants/lib/netstat/Cargo.toml [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+    "Win32_Foundation",
+    "Win32_Networking",
+    "Win32_NetworkManagement_IpHelper",
+    "Win32_System_ProcessStatus",
+    "Win32_System_Threading",
+    "Win32_System_Diagnostics_ToolHelp",
+]}
+
+[target.'cfg(target_os = "macos")'.dependencies]
+libc = "0.2"
```
Comment (hulto) [inline implants/lib/netstat/Cargo.toml]: Move these to workspace root

File: implants/lib/netstat/src/macos.rs [hunk 6]
```diff
@@ -0,0 +1,653 @@
...
+    fn proc_name(pid: libc::c_int, buffer: *mut libc::c_void, buffersize: u32) -> libc::c_int;
+}
+
+// Constants from libproc.h
+const PROC_ALL_PIDS: u32 = 1;
+const PROC_PIDLISTFDS: libc::c_int = 1;
+const PROC_PIDFDSOCKETINFO: libc::c_int = 3;
+const PROC_FDTYPE_SOCKET: u32 = 2;
+
+// Data structures matching macOS kernel structures
```
Comment (hulto) [inline implants/lib/netstat/src/macos.rs:41]: Add comment about where to derive these.

File: implants/lib/netstat/src/macos.rs [hunk 7]
```diff
@@ -0,0 +1,653 @@
...
+    tcpsi_ini: InSockInfo,
+    tcpsi_state: libc::c_int,
+    tcpsi_timer: [libc::c_int; 4],
+    tcpsi_mss: libc::c_int,
+    tcpsi_flags: u32,
+    rfu_1: u32,
+    tcpsi_tp: u64,
+}
+
+const SOCK_MAXADDRLEN: usize = 255;
```
Comment (hulto) [inline implants/lib/netstat/src/macos.rs:219]: Put these with other consts

File: implants/lib/netstat/src/macos.rs [hunk 8]
```diff
@@ -0,0 +1,653 @@
...
+    kcsi_flags: u32,
+    kcsi_recvbufsize: u32,
+    kcsi_sendbufsize: u32,
+    kcsi_unit: u32,
+    kcsi_name: [u8; MAX_KCTL_NAME],
+}
+
+#[repr(C)]
+#[derive(Copy, Clone)]
+struct VsockSockInfo {
```
Comment (hulto) [inline implants/lib/netstat/src/macos.rs:277]: Make sure all these structs are used.

File: implants/lib/netstat/src/macos.rs [hunk 9]
```diff
@@ -0,0 +1,653 @@
...
+/// Checks if the current macOS version is 11.0 or greater.
+/// The proc_info.h structures used here, particularly vsock_sockinfo,
+/// were added in macOS 11.0 (Big Sur) with the Virtualization framework.
+fn check_macos_version() -> Result<()> {
+    use std::ffi::CStr;
+
+    unsafe {
+        // Use sysctl to get kern.osproductversion
+        let mut size: libc::size_t = 0;
+        let name = b"kern.osproductversion\0";
```
Comment (hulto) [inline implants/lib/netstat/src/macos.rs:293]: Make this a Cstr?

File: implants/lib/netstat/src/macos.rs [hunk 10]
```diff
@@ -0,0 +1,653 @@
...
+            std::ptr::null_mut(),
+            &mut size,
+            std::ptr::null_mut(),
+            0,
+        );
+
+        if result != 0 {
+            return Err(anyhow!("Failed to get macOS version via sysctl"));
+        }
+
```
Comment (hulto) [inline implants/lib/netstat/src/macos.rs:307]: Maybe sanity check size here.

File: implants/lib/netstat/src/macos.rs [hunk 11]
```diff
@@ -0,0 +1,653 @@
...
+        };
+
+        // Get process name
+        let process_name = get_process_name(pid).ok();
+
+        // Parse socket info based on family
+        match si.soi_family {
+            libc::AF_INET => {
+                // IPv4
+                let in_info = si.soi_proto.pri_in;
```
Comment (hulto) [inline implants/lib/netstat/src/macos.rs]: Move outide match

File: implants/lib/netstat/src/macos.rs [hunk 12]
```diff
@@ -0,0 +1,653 @@
...
+
+                let local_addr = in_info.insi_laddr.ina_46.i46a_addr4.s_addr;
+                let remote_addr = in_info.insi_faddr.ina_46.i46a_addr4.s_addr;
+
+                let local_port = u16::from_be((in_info.insi_lport & 0xFFFF) as u16);
```
Comment (hulto) [inline implants/lib/netstat/src/macos.rs]: Move outside match

File: implants/lib/netstat/src/macos.rs [hunk 13]
```diff
@@ -0,0 +1,653 @@
...
+                let remote_port = u16::from_be((in_info.insi_fport & 0xFFFF) as u16);
+
+                let remote_address = if remote_addr == 0 {
+                    None
+                } else {
+                    Some(IpAddr::V4(Ipv4Addr::from(u32::from_be(remote_addr))))
+                };
+
+                let connection_state = if socket_type == SocketType::TCP {
```
Comment (hulto) [inline implants/lib/netstat/src/macos.rs]: Move outside match

File: implants/lib/netstat/src/windows.rs [hunk 14]
```diff
@@ -0,0 +1,443 @@
...
+    // Get UDP IPv6 sockets
+    entries.extend(get_udp6_table(&process_map)?);
+
+    Ok(entries)
+}
+
+fn get_tcp_table(process_map: &HashMap<u32, String>) -> Result<Vec<NetstatEntry>> {
+    unsafe {
+        let mut size: u32 = 0;
+
```
Comment (hulto) [inline implants/lib/netstat/src/windows.rs:46]: Is there ever a time where a windows process might have additional privs to see more processes that we want to leverage like SeDebug?

**Comment by KCarretto** [comment]
imho we should make the changes to `eldritchv2-final` and fix forward

File: implants/lib/eldritchv2/stdlib/eldritch-libprocess/Cargo.toml [hunk 15]
```diff
@@ -9,8 +9,13 @@ eldritch-macros = { workspace = true }
 sysinfo = { workspace = true, optional = true }
 listeners = { workspace = true, optional = true }
```
Comment (KCarretto) [inline implants/lib/eldritchv2/stdlib/eldritch-libprocess/Cargo.toml]: do we still need listeners?

Comment (hulto) [reply implants/lib/eldritchv2/stdlib/eldritch-libprocess/Cargo.toml]: Good catch ty

**Review by KCarretto — APPROVED** [review]
