### PR TITLE
622 file list tome doesnt support relative paths

### LINKED ISSUE #622: file_list tome doesn't support relative paths
**Describe the bug**
image

Expected to see my current dir but go `/`
image

This seems to be the culprit
image

### PR DESCRIPTION
**Pull request by hulto**
#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
* fixes file_list tome
* Moves file.list eldritch tests to new end to end style

#### Which issue(s) this PR fixes:
Fixes #622

### CODE REVIEW

File: implants/lib/eldritch/src/file/list_impl.rs [hunk 1]
```diff
@@ -208,12 +208,66 @@ pub fn list(starlark_heap: &Heap, path: String) -> Result<Vec<Dict>> {
...
+    use std::collections::HashMap;
+
+    use crate::runtime::Message;
+
     use super::*;
-    use tempfile::tempdir;
+    use pb::eldritch::Tome;
+    use tempfile::{tempdir, NamedTempFile};
+
+    fn init_logging() {
```
Comment (KCarretto) [inline implants/lib/eldritch/src/file/list_impl.rs:219]: nit: Perhaps it's time to create a logging crate

**Review by KCarretto — APPROVED** [review]

File: implants/lib/eldritch/src/file/list_impl.rs (hunk 1 above)
Comment (hulto) [reply implants/lib/eldritch/src/file/list_impl.rs:219]: I agree - can you add it as an issue for after ISTS.
