### PR TITLE
fix: fix #1516

### LINKED ISSUE #1516: [bug] Update agent.get_config() to return a platform and type string instead of int.
**Describe the bug**
`agent.get_config()` returns an int for platform should return a string representation `PLATFORM_WINDOWS` or `PLATFORM_LINUX` etc.

Image

**Resolution**
Update the `/workspaces/realm/implants/imixv2/src/agent.rs` `get_config` implementation to return platform and type as a human readable string instead of the Enums int value.

### PR DESCRIPTION
**Pull request by simbiont666**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes platform and type string representation for `agent.get_config()`

#### Which issue(s) this PR fixes:

Fixes #1516

### CODE REVIEW

File: implants/imixv2/src/agent.rs [hunk 1]
```diff
@@ -1,5 +1,7 @@
 use anyhow::{Context, Result};
 use eldritch_agent::Agent;
+use pb::c2::active_transport::Type;
```
Comment (KCarretto) [inline implants/imixv2/src/agent.rs:3]: @hulto is this available_transport now?

**Review by KCarretto — APPROVED** [review]
image
